### Fetch all products with optional query parameters
GET {{protocol}}{{host}}:{{port}}}//products?author={{author}}&price={{price}}
Accept: application/json

###

### Fetch a specific product by ID
GET {{protocol}}{{host}}:{{port}}}//products/{{productId}}
Accept: application/json

###

### Fetch all users
GET {{protocol}}{{host}}:{{port}}}//users
Accept: application/json

###

### Fetch a specific user by ID
GET {{protocol}}{{host}}:{{port}}}//users/{{userId}}
Accept: application/json

###

### Fetch bids for a specific product
GET {{protocol}}{{host}}:{{port}}}//products/{{productId}}/bids
Accept: application/json

###

### Fetch bids made by a specific user
GET {{protocol}}{{host}}:{{port}}}//users/{{userId}}/bids
Accept: application/json

###
