### Create a new product
POST {{protocol}}{{host}}:{{port}}}/products
Content-Type: application/json

{
  "product": {
    "id": "123",
    "name": "Art Piece",
    "author": "John Doe",
    "year": "2023",
    "startBidTime": "2023-09-10T10:00:00Z",
    "endBidTime": "2023-09-20T10:00:00Z",
    "basePrice": "100"
  }
}

###

### Create a new user
POST {{protocol}}{{host}}:{{port}}}//users
Content-Type: application/json

{
  "user": {
    "id": "user1",
    "username": "johnD",
    "password": "pass",
    "role": "user",
    "contact": {
      "email": "john@example.com",
      "phone": "+1234567890"
    }
  }
}

###

### Add a bid to a product
POST {{protocol}}{{host}}:{{port}}}//products/{{productId}}/bids
Content-Type: application/json

{
  "bid": {
    "productId": "{{productId}}",
    "userId": "user1",
    "bidTime": "2023-09-10T11:00:00Z",
    "bidPrice": "110"
  }
}

###
