export const productsJsonPath = "./src/resources/products.json";
export const usersJsonPath = "./src/resources/users.json";
export let secret = "InthebeginningGodcreatedtheheavenandtheearth.2Andtheearthwaswithoutform,andvoid;anddarknesswasuponthefaceofthedeep.AndtheSpiritofGodmoveduponthefaceofthewaters.3AndGodsaid,Lettherebelight:andtherewaslight.4AndGodsawthelight,thatitwasgood:andGoddividedthelightfromthedarkness.5AndGodcalledthelightDay,andthedarknesshecalledNight.Andtheeveningandthemorning"
